- name: Docker – dokumentáció
  href: index.yml
- name: Első lépések
  expanded: true
  items:
    - name: Ubuntu rendszerű virtuális gép üzembe helyezése a Dockerrel
      href: 'https://azure.microsoft.com/resources/templates/docker-simple-on-ubuntu/'
- name: Oktatóanyagok
  items:
    - name: Python-webapp a Docker és a PostgreSQL használatával
      href: ../app-service/tutorial-python-postgresql-app.md?toc=%2fazure%2fpostgresql%2ftoc.json
    - name: 'CI/CD a Docker, a Jenkins és a Linux használatával'
      href: /azure/jenkins/tutorial-jenkins-github-docker-cicd
- name: Útmutatók
  items:
    - name: Docker virtuálisgép-bővítmény
      href: /azure/virtual-machines/linux/dockerextension
    - name: Docker Machine
      href: /azure/virtual-machines/linux/docker-machine
    - name: Docker tárolóregisztrációs adatbázis
      href: /azure/container-registry/container-registry-get-started-portal
- name: További források
  items:
    - name: Azure-ütemterv
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Docker Azure-illesztő
      href: 'https://docs.docker.com/machine/drivers/azure/'
    - name: Docker Azure-hely
      href: 'https://www.docker.com/docker-azure'
    - name: Docker-hely
      href: 'https://docker.com'