items:
- name: Ansible az Azure-ban – dokumentáció
  href: ./index.yml
- name: Áttekintés
  items:
  - name: Ansible az Azure-ban – ismertetés
    href: ./ansible-overview.md
- name: Gyors útmutatók
  items:
  - name: Az Ansible telepítése Linux rendszerű virtuális gépen
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Linux rendszerű virtuális gép létrehozása
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Linux rendszerű virtuális gép kezelése
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  expanded: true
- name: Oktatóanyagok
  items:
  - name: Forgatókönyv futtatása a Cloud Shellben
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Dinamikus leltárak kezelése
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
  - name: VMSS létrehozása és konfigurálása
    href: ./ansible-create-configure-vmss.md
  - name: Alkalmazás üzembe helyezése a VMSS-en
    href: ./ansible-deploy-app-vmss.md
  - name: AKS-fürtök létrehozása és konfigurálása
    href: ./ansible-create-configure-aks.md
  - name: Azure Application Gateway létrehozása és konfigurálása
    href: ./ansible-create-configure-application-gateway.md
  - name: MySQL-hez készült Azure DB létrehozása és konfigurálása
    href: ./ansible-create-configure-mysql.md
  - name: Azure Web Apps-alkalmazások létrehozása és konfigurálása
    href: ./ansible-create-configure-azure-web-apps.md
- name: Referencia
  items:
  - name: Forgatókönyv-szerepkörök
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Kiadások és szolgáltatások
    href: ./ansible-matrix.md
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Terheléselosztók
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Virtual machines (Virtuális gépek)
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Minden modul az Azure-ban
    href: https://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Eszközök
  items:
  - name: Visual Studio Code-bővítmény az Ansible-höz
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: 4190429ddd0189c937577257f07a21fcf6687ad2
ms.sourcegitcommit: 5d837a7557363424e0183d5f04dcb23a8ff966bb
ms.translationtype: HT
ms.contentlocale: hu-HU
ms.lasthandoff: 12/06/2018
ms.locfileid: "52966534"
