items:
- name: Ansible az Azure-ban – dokumentáció
  href: ./index.yml
- name: Áttekintés
  items:
  - name: Ansible az Azure-ban – ismertetés
    href: ./ansible-overview.md
- name: Gyors útmutatók
  items:
  - name: Az Ansible telepítése Linux rendszerű virtuális gépen
    href: /azure/virtual-machines/linux/ansible-install-configure
    maintainContext: true
  - name: Linux rendszerű virtuális gép létrehozása
    href: /azure/virtual-machines/linux/ansible-create-vm
    maintainContext: true
  - name: Linux rendszerű virtuális gép kezelése
    href: /azure/virtual-machines/linux/ansible-manage-linux-vm
    maintainContext: true
  - name: Forgatókönyv futtatása a Cloud Shellben
    href: ./ansible-run-playbook-in-cloudshell.md
  expanded: true
- name: Oktatóanyagok
  items:
  - name: AKS
    items:
    - name: AKS-fürtök létrehozása és konfigurálása
      href: ./ansible-create-configure-aks.md
  - name: App Service
    items:
    - name: Azure Web Apps-alkalmazások létrehozása és konfigurálása
      href: ./ansible-create-configure-azure-web-apps.md
    - name: Az Azure Web Apps skálázása
      href: ./ansible-scale-azure-web-apps.md
  - name: Application Gateway
    items:
    - name: Azure Application Gateway létrehozása és konfigurálása
      href: ./ansible-create-configure-application-gateway.md
  - name: Adatbázisok
    items:
    - name: MySQL-hez készült Azure DB létrehozása és konfigurálása
      href: ./ansible-create-configure-mysql.md
  - name: Dinamikus leltár
    items:
    - name: Dinamikus leltárak kezelése
      href: ./ansible-manage-azure-dynamic-inventories.md
  - name: Virtuális hálózat
    items:
    - name: Útválasztási táblázatok létrehozása és konfigurálása
      href: ./ansible-create-configure-route-table.md
  - name: VMSS
    items:
    - name: VMSS létrehozása és konfigurálása
      href: ./ansible-create-configure-vmss.md
    - name: Alkalmazás üzembe helyezése a VMSS-en
      href: ./ansible-deploy-app-vmss.md
    - name: VMSS automatikus skálázása
      href: ./ansible-auto-scale-vmss.md
- name: Referencia
  items:
  - name: Forgatókönyv-szerepkörök
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Kiadások és szolgáltatások
    href: ./ansible-matrix.md
  - name: Azure Container Instances
    href: https://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: https://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Terheléselosztók
    href: https://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Virtual machines (Virtuális gépek)
    href: https://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: Minden modul az Azure-ban
    href: https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure
- name: Eszközök
  items:
  - name: Visual Studio Code-bővítmény az Ansible-höz
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible
ms.openlocfilehash: b14bcd85be13a29d179606206ff7cfd8a69a5179
ms.sourcegitcommit: 82cdc26615829df3c57ee230d99eecfa1c4ba459
ms.translationtype: HT
ms.contentlocale: hu-HU
ms.lasthandoff: 01/19/2019
ms.locfileid: "54413498"
