- name: A Kubernetes az Azure-on
  href: ./index.yml
- name: Áttekintés
- name: Rövid útmutatók
  expanded: true
- name: Oktatóanyagok
- name: Alapelvek
- name: Útmutatók
  items:
    - name: Adatok megőrzése az Azure Files segítségével
      href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
    - name: Figyelés
    - name: Spring Boot-alkalmazások üzembe helyezése
      items:
        - name: Spring Boot-alkalmazás üzembe helyezése Linux rendszeren az Azure Container Service-ben
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Spring Boot-alkalmazás üzembe helyezése Kubernetes-fürtön az Azure Container Service-ben
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: Spring Boot-alkalmazás üzembe helyezése a fabric8 Maven bővítménnyel
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Referencia
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: További források
  items:
    - name: Azure-ütemterv
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Sablonok – ACS Engine
      href: 'https://github.com/Azure/acs-engine'
    - name: Díjszabás
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Régiónkénti elérhetőség
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videók
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'