### YamlMime:Landing
title: Azure Arc Kubernetes (előzetes verzió)
summary: Tudnivalók a Kubernetes-fürtök Azure Arc segítségével történő kezeléséről
metadata:
  title: Azure Arc Kubernetes
  description: Tudnivalók a helyszíni gépek Azure-ban történő felügyeletéről
  author: 
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 06/26/2020
  ms.author: 
  ms.openlocfilehash: 7c643d10971d93a3c6194bc7390d2271c1ed561b
  ms.sourcegitcommit: e2b36c60a53904ecf3b99b3f1d36be00fbde24fb
  ms.translationtype: HT
  ms.contentlocale: hu-HU
  ms.lasthandoff: 08/24/2020
  ms.locfileid: "88763737"
landingContent:
- title: Kubernetes-fürtök csatlakoztatása az Azure-hoz az Azure Arc használatával
  linkLists:
  - linkListType: overview
    links:
    - text: Mi az Azure Arc-kompatibilis Kubernetes?
      url: overview.md
  - linkListType: quickstart
    links:
    - text: Fürt csatlakoztatása
      url: connect-cluster.md
  - linkListType: how-to-guide
    links:
    - text: Konfigurációk üzembe helyezése GitOps használatával
      url: use-gitops-connected-cluster.md
    - text: Helm-diagramok üzembe helyezése GitOps használatával
      url: use-gitops-with-helm.md
    - text: GitOps kényszerítése az Azure Policyval
      url: use-azure-policy.md
    - text: Azure IoT Edge számítási feladatok üzembe helyezése
      url: deploy-azure-iot-edge-workloads.md
